---
# Source: fleetms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "fleetms-service"
  labels:
    chart: "fleetms-1.0.0"
spec:
  selector:
    app: "fleetms-selector"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
