apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "voyagesms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "voyagesms"
        env:
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: "kcontainer-es-kbsf"
                key: kafka_brokers_sasl_flat
          - name: ORDER_TOPIC
            value: "orders"
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "kcontainer-es"
                key: api_key
    
        
