language: python
sudo: 'required'

dist: xenial
services:
  - 'docker'

before_install:
  - echo "to be done"

script:
  - echo "to be done"

after_success:
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && cd kcontainer && make build-changed || echo "success"

#  build only master and tagged/branch releases.
branches:
  only: 
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

deploy:
  skip_cleanup: true
  provider: script
  script: bash -c "cd kcontainer && make push-changed"
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^master|[0-9]+\..*|v[0-9]+\..*|release-[0-9]+\..*$
