apiVersion: v1
kind: Service
metadata:
  name: "orderqueryms-service"
  labels:
    chart: "orderqueryms-1.0.0"
spec:
  selector:
    app: "orderqueryms-selector"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
