apiVersion: apps/v1
kind: Deployment
metadata:
  name: "voyagesms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "voyagesms"
        env:
          - name: ORDER_ENDPOINT
            value: http://orders-kn-channel.kcontainer.svc.cluster.local   
