apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "voyagesms-service"
spec:
  selector:
    app: "voyagesms-selector"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000