---
# Source: springcontainerms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "springcontainerms-service"
  labels:
    chart: "springcontainerms-1.0.0"
spec:
  selector:
    app: "springcontainerms-selector"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
