apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ordercommandms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "ordercommandms"
        image: "eventingapps/order-command-ms:1.0.0"
        imagePullPolicy: Always