apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Service
metadata:
  name: kcontainer-postgresql
spec:
  plan: standard
  serviceClass: databases-for-postgresql
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Binding
metadata:
  name: kcontainer-postgresql
spec:
  serviceName: kcontainer-postgresql