apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: containers
spec:
  bindingFrom:
    name: kcontainer-es
  topicName: containers
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: orders
spec:
  bindingFrom:
    name: kcontainer-es
  topicName: orders
---
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: rejected-orders
spec:
  bindingFrom:
    name: kcontainer-es
  topicName: rejected-orders
---  
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Topic
metadata:
  name: allocated-orders
spec:
  bindingFrom:
    name: kcontainer-es
  topicName: allocated-orders
