apiVersion: skaffold/v2alpha3
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}"
  artifacts:
    - image: eventingapps/spring-container-ms
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - 'src/**/*.java'
deploy:
 kustomize:
    paths: ["k8s/overlays/knative-eventing-dev"]