apiVersion: skaffold/v2alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}"
  artifacts:
    - image: us.icr.io/paolo/kc-spring-container-ms
      context: .
      docker:
        dockerfile: Dockerfile.dev
      sync:
        infer:
          - 'src/**/*.java'
deploy:
  kubectl:
    manifests:
      - k8s/deployment-knative.yaml
      - k8s/service.yaml