apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: fleetms-bluewatershipevents
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: bluewatership
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: fleetms-service
    uri: /bluewatershipevents
---    
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: fleetms-bluewatercontainerevents
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: bluewatercontainer
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: fleetms-service
    uri: /bluewatercontainerevents 