---
# Source: voyagesms/templates/deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "voyagesms-deployment"
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: "voyagesms-selector"
        version: "current"
    spec:
      serviceAccountName: default
      containers:
      - name: "voyagesms"
        image: "us.icr.io/paolo/kc-voyages-ms:latest"
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 3000
          periodSeconds: 1000
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: PORT
            value : "3000"
          - name: APPLICATION_NAME
            value: "voyagesms"
          - name: KAFKA_BROKERS
            valueFrom:
              secretKeyRef:
                name: "kcontainer-es-kbsf"
                key: kafka_brokers_sasl_flat
          - name: ORDER_TOPIC
            value: "orders"
          - name: KAFKA_APIKEY
            valueFrom:
              secretKeyRef:
                name: "kcontainer-es"
                key: api_key
