---
# Source: voyagesms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "voyagesms-service"
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    nodePort: 31000
  selector:
    app: "voyagesms-selector"
