apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: refarch-kc-bluewatership
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: bluewatership
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: kc-ui-service
    uri: /api/bluewatershipevents
---
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: refarch-kc-bluewaterproblem
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: bluewaterproblem
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: kc-ui-service
    uri: /api/bluewaterproblemevents      

 