apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "springcontainerms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "springcontainerms"
        env:
          - name: ORDER_ENDPOINT
            value: http://orders-kn-channel.kcontainer.svc.cluster.local
          - name: CONTAINER_ENDPOINT
            value: http://containers-kn-channel.kcontainer.svc.cluster.local  