apiVersion: apps/v1
kind: Deployment
metadata:
  name: "fleetms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "fleetms"
        env:
          - name: BLUEWATER_SHIP_ENDPOINT
            value: http://bluewatership-kn-channel.kcontainer.svc.cluster.local
          - name: BLUEWATER_CONTAINER_ENDPOINT  
            value: http://bluewatercontainer-kn-channel.kcontainer.svc.cluster.local       
