apiVersion: apps/v1
kind: Deployment
metadata:
  name: kc-ui
  labels:
    app: kc-ui
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: kc-ui
  template:
    metadata:
      labels:
        app: kc-ui
    spec:
      serviceAccountName: default
      containers:
      - name: "kc-ui"
        image: "eventingapps/kcontainer-ui"
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3010
          initialDelaySeconds: 3000
          periodSeconds: 1000
        ports:
        - containerPort: 3010
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: APPLICATION_NAME
            value: "kc-ui"
          - name: PORT
            value : "3010"
          - name: FLEETMS_SERVICE_HOST
            value: "fleetms-service"
          - name: FLEETMS_SERVICE_PORT
            value: "80"
          - name: ORDERCOMMANDMS_SERVICE_HOST
            value: "ordercommandms-service"
          - name: ORDERCOMMANDMS_SERVICE_PORT
            value: "80"
          - name: ORDERQUERYMS_SERVICE_HOST
            value: "orderqueryms-service"
          - name: ORDERQUERYMS_SERVICE_PORT
            value: "80"
          - name: CONTAINERMS_SERVICE_HOST
            value: "springcontainerms-service"            
          - name: CONTAINERMS_SERVICE_PORT
            value: "80"  
          - name: VOYAGESMS_SERVICE_HOST
            value: "voyagesms-service"
          - name: VOYAGESMS_SERVICE_PORT
            value: "80"
