apiVersion: apps/v1
kind: Deployment
metadata:
  name: "springcontainerms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "springcontainerms"
        image: "eventingapps/spring-container-ms:1.0.0"
        imagePullPolicy: Always