---
# Source: voyagesms/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: "voyagesms-service"
  labels:
    chart: "voyagesms-1.0.0"
spec:
  selector:
    app: "voyagesms-selector"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
