apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ordercommandms-deployment"
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: ordercommandms-selector
  template:
    metadata:
      labels:
        app: "ordercommandms-selector"
        version: "current"
    spec:
      containers:
      - name: "ordercommandms"
        image: "us.icr.io/paolo/order-command-ms"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "200m"
            memory: "300Mi"
        env:
          - name: APPLICATION_NAME
            value: ordercommandms
