apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "orderqueryms-deployment"
spec:
  template:
    spec:
      containers:
      - name: "orderqueryms"
        env:
          - name: ERROR_ENDPOINT
            value: http://errors-kn-channel.kcontainer.svc.cluster.local            
